name: cmake build macOS

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: cmake -B build
    - name: build
      run: cmake --build build
    - name: test
      run: ${{ github.workspace }}/build/tests/run_tests
